# 1. array의 이해
## 1) numpy array의 특정
1. 메모리 공간에 연속적으로 동일한 간격으로 저장되어있다.
<br> - 메모리 상에는 항상 1차원으로 저장된다.
<br> - 데이터는 항상 행우선 순위로 저장된다
<br> - arr를 모양을 바꾸어서 읽을 수 있다. ndim=1이면 벡터라고 부른다. ndim=2이면 행렬이라고 부른다. ndim>2이면 텐서라고 부른다 .
2. 각 성분은 모두 동일한 dtype을 갖는다.
3. 3. 연산할 때 한번에 연산이 이루어진다.
numpy = array 속성 + array 연산

## 2) numpy array를 둘러싼 생태계
- scipy : 과학기술 연산
- matplotlib : 시각화를 위한 base 패키지
- pandas :데이터 변환, 추출, sqlike 연산
- statmodels : 통계 툴
- scikit-learn : 머신러닝
- tensorflow : 딥러닝
- pytorch : 딥러닝
## 3) array의 주요 속성

In [22]:
import numpy as np

In [23]:
a1d = np.arange(24)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
a3d = a1d.reshape((2,3,4))
a3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
A = a3d[0, :, :2]
A

array([[0, 1],
       [4, 5],
       [8, 9]])

In [26]:
a3d[0][:,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [27]:
a3d[[1]].shape

(1, 3, 4)

In [28]:
a1d = np.arange(24)
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
bv = a1d % 3 == 0
bv

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False])

In [30]:
A = a1d[bv]
A

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [31]:
A[1] = -5
a1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
arr = np.array([3, 7, 6, 9])
arr

array([3, 7, 6, 9])

In [33]:
arr.ndim

1

In [35]:
arr.shape

(4,)

In [36]:
arr.size

4

In [37]:
arr.dtype

dtype('int32')

In [38]:
arr.astype('int32')

array([3, 7, 6, 9])

In [41]:
farr = arr.astype('float')
farr.dtype

dtype('float64')

In [42]:
farr[1] = -1
farr

array([ 3., -1.,  6.,  9.])

In [43]:
arr

array([3, 7, 6, 9])

In [44]:
ar2d = arr.reshape((2, 2))
ar2d

array([[3, 7],
       [6, 9]])

In [45]:
ar2d[1, 0] = 50
ar2d

array([[ 3,  7],
       [50,  9]])

In [46]:
#1. 변한다. 2. 안변한다.
arr

array([ 3,  7, 50,  9])

In [47]:
ar3d = np.arange(60).reshape((3,4,5))
ar3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

## 2. array의 색인
### 1) 점색인
차원이 축소된다.

In [48]:
arr

array([ 3,  7, 50,  9])

In [49]:
# 점색인 : 0 ~ size -1
arr[-2]

50

In [50]:
ar2d[:,-2]

array([ 3, 50])

In [51]:
ar2d.shape

(2, 2)

In [52]:
ar3d[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
ar3d[0][0]

array([0, 1, 2, 3, 4])

In [54]:
ar3d[1, : 2]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [55]:
# 43, 48, 53, 58
# ar3d = np.arange(60).reshape((3,4,5))
ar3d[2,:,-2]

array([43, 48, 53, 58])

## 2) 불연속 색인
- 점색인을 여러번하는것.
- 점색인할 주소를 리스트로 전달
- 차원 축소는 발생하지 않는다.

In [56]:
arr

array([ 3,  7, 50,  9])

In [58]:
arr[[0,2]]

array([ 3, 50])

In [59]:
ar2d

array([[ 3,  7],
       [50,  9]])

In [60]:
ar2d[[1,0], :]

array([[50,  9],
       [ 3,  7]])

연속된 불연속 색인은 차원을 축소시키고, pairwise point indexing을 수행한다.

In [61]:
ar2d[[1, 0], [0,1]]

array([50,  7])

In [62]:
# 50, 7, 3을 가져오고 싶다.
# ar2d = np.array([3,7,50,9].reshape((2,2))
ar2d[[1, 0, 0], [0,1,0]]

array([50,  7,  3])

In [63]:
# 9,7,3을 가져오세요
ar2d[[1,0,0], [1,0,1]]

array([9, 3, 7])

In [66]:
# 7,3을 가져오고 싶다.
ar2d[0, [1,0]]
ar2d[[0,0],[1,0]]
ar2d[0][::-1]
ar2d[0][[1,0]]

array([7, 3])

In [67]:
ar3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [68]:
ar3d[[0,2],:,2]
ar3d[[0,2]][:,:,[2,4]]

array([[[ 2,  4],
        [ 7,  9],
        [12, 14],
        [17, 19]],

       [[42, 44],
        [47, 49],
        [52, 54],
        [57, 59]]])

In [69]:
# good job!
tmp = ar3d[[0,0,2,2],:,[2,4,2,4]]
tmp

array([[ 2,  7, 12, 17],
       [ 4,  9, 14, 19],
       [42, 47, 52, 57],
       [44, 49, 54, 59]])

In [71]:
tmp.T

array([[ 2,  4, 42, 44],
       [ 7,  9, 47, 49],
       [12, 14, 52, 54],
       [17, 19, 57, 59]])

In [72]:
tmp2 = tmp.reshape(2,2,4)
tmp2

array([[[ 2,  7, 12, 17],
        [ 4,  9, 14, 19]],

       [[42, 47, 52, 57],
        [44, 49, 54, 59]]])

In [74]:
t1, t2 = tmp.reshape((2,2,4))
t1.T

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19]])

In [75]:
t2.T

array([[42, 44],
       [47, 49],
       [52, 54],
       [57, 59]])

In [76]:
np.vstack((t1.T, t2.T)).reshape((2,4,2))

array([[[ 2,  4],
        [ 7,  9],
        [12, 14],
        [17, 19]],

       [[42, 44],
        [47, 49],
        [52, 54],
        [57, 59]]])

In [78]:
tmp3 = np.swapaxes(tmp.reshape((2,2,4)), 1, 2)
tmp3

array([[[ 2,  4],
        [ 7,  9],
        [12, 14],
        [17, 19]],

       [[42, 44],
        [47, 49],
        [52, 54],
        [57, 59]]])

In [79]:
tmp2

array([[[ 2,  7, 12, 17],
        [ 4,  9, 14, 19]],

       [[42, 47, 52, 57],
        [44, 49, 54, 59]]])

In [81]:
tmp2[0,0,1], tmp2[0,1,0]

(7, 4)

tmp3 = np.swapaxes(tmp2,1,2)
tmp2[:,i,j] = tmp3[:,j,i]
- :axis 0
- i = axis 1
- j = axis 2

In [82]:
ar2d.T[0,1] == ar2d[1,0]

True

### 3) 연속 색인
arr[start:end:(-)step]
- start 포함
- end 포함하지 않고, overflow를 허용
- 차원 축소가 발새하지 않는다.
- -는 방향을 반대로 하여 가져온다

In [83]:
arr

array([ 3,  7, 50,  9])

In [85]:
arr[2:3]

array([50])

In [86]:
arr[2]

50

In [87]:
arr[::-3]

array([9, 3])

In [88]:
tmp

array([[ 2,  7, 12, 17],
       [ 4,  9, 14, 19],
       [42, 47, 52, 57],
       [44, 49, 54, 59]])

In [89]:
tmp[1:3,1:]

array([[ 9, 14, 19],
       [47, 52, 57]])

In [90]:
tmp[:, [0,3]]

array([[ 2, 17],
       [ 4, 19],
       [42, 57],
       [44, 59]])

In [92]:
tmp[:,::3]

array([[ 2, 17],
       [ 4, 19],
       [42, 57],
       [44, 59]])

In [95]:
arr

array([ 3,  7, 50,  9])

ar2d는 arr을 reshape 한것으로 arr은 메모리상에 1차원으로 연속되어 있고, ar2dsms 이를 2차원으로 읽는다.
- ar2d는 arr의 view라고 한다.
- 이때 view에 값을 쓰면 원래 arr의 값이 변경된다.
- view의 referance의 성분에 값을 쓰면:
- view가 연속색인인 경우, 값이 변경되고 ref는 view를 유지
- view가 불연속색인인 경우 갑이 변경되지 않는다.(ref는 복사가 이뤄진다.)

In [96]:
ar2d

array([[ 3,  7],
       [50,  9]])

In [98]:
arr[0] = 2
ar2d

array([[ 2,  7],
       [50,  9]])

In [99]:
k = arr[0]
k

2

In [101]:
k = 5
# 1. arr가 변경된다. 2. 변경 안된다.
arr

array([ 2,  7, 50,  9])

In [102]:
# k는 arr의 일부분을 바라보는 View를 유지
k = arr[:2]
k

array([2, 7])

In [103]:
# 1. arr가 변경된다. 2. 변경 안된다.
k[0] = 5
arr

array([ 5,  7, 50,  9])

In [104]:
# 메모리에 연속되어 있으려면, 바라볼 수 가 없다. 복사가 이루어진다.
k = arr[[0,2]]
k

array([ 5, 50])

In [105]:
# 1. arr가 변경된다. 2. 변경 안된다.
k[0] = 3
arr

array([ 5,  7, 50,  9])

In [106]:
k

array([ 3, 50])

In [107]:
# 불연속색인에 대한 직접적인 대입은 arr를 변경시킨다.
arr[[0,3]] = 7
arr

array([ 7,  7, 50,  7])

### 5) 불리언색인(논리색인)
fancy indexing(팬시 색인, 불연속 색인)으로 대체될 수 있다.

In [108]:
arr

array([ 7,  7, 50,  7])

In [109]:
bv = np.array([True, True, False, True])
bv

array([ True,  True, False,  True])

In [110]:
arr[bv]

array([7, 7, 7])

In [111]:
tmp

array([[ 2,  7, 12, 17],
       [ 4,  9, 14, 19],
       [42, 47, 52, 57],
       [44, 49, 54, 59]])

In [112]:
tmp[:, bv]

array([[ 2,  7, 17],
       [ 4,  9, 19],
       [42, 47, 57],
       [44, 49, 59]])

In [113]:
tmp[:, [0,1,3]]

array([[ 2,  7, 17],
       [ 4,  9, 19],
       [42, 47, 57],
       [44, 49, 59]])

#### pairwise indexing
fancy 색인을 행과 열에 맞추어 쌍별로 수행한것. 개념적으로 행과 열의 쌍에 대한 점색인을 여러번 한것이기 때문에, 차원이 축소된다.

In [115]:
tmp

array([[ 2,  7, 12, 17],
       [ 4,  9, 14, 19],
       [42, 47, 52, 57],
       [44, 49, 54, 59]])

In [116]:
tmp[[1,0,2], [0,1,2]]

array([ 4,  7, 52])

In [117]:
## 4, 17, 2를 가져오고 싶다.
a3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [118]:
a3d[[0,1,0],[1,1,0],[0,1,2]]

array([ 4, 17,  2])

## 3. array의 연산
- 연산자를 이용한 연산 +, -, *, / ...
- 메소드 또는 함수를 이용한 연산
#### 1) 연산자를 이용한 연산
스칼라와의 연산은 brodcasting을 발생시킨다.

In [119]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [120]:
arr + 1

array([1, 2, 3, 4])

In [121]:
arr + 10

array([10, 11, 12, 13])

In [122]:
arr - 1

array([-1,  0,  1,  2])

In [123]:
arr * 3

array([0, 3, 6, 9])

In [124]:
arr * 1.2

array([0. , 1.2, 2.4, 3.6])

In [125]:
arr /.2

array([ 0.,  5., 10., 15.])

In [126]:
arr ** 2

array([0, 1, 4, 9], dtype=int32)

동일한 shape의 array 간의 연산은 elementwise-operation이 발생

In [128]:
tmp[0]

array([ 2,  7, 12, 17])

In [129]:
tmp[0] + arr

array([ 2,  8, 14, 20])

In [130]:
tmp[0] * arr

array([ 0,  7, 24, 51])

shape이 다른 array간 연산은 brodcasting후 elementwise operation이 발생한다.

In [131]:
tmp + arr

array([[ 2,  8, 14, 20],
       [ 4, 10, 16, 22],
       [42, 48, 54, 60],
       [44, 50, 56, 62]])

In [132]:
arr

array([0, 1, 2, 3])

In [133]:
tmp

array([[ 2,  7, 12, 17],
       [ 4,  9, 14, 19],
       [42, 47, 52, 57],
       [44, 49, 54, 59]])

[Quiz] arr를 세로로 세워서 덧셈연산을 수행하려면 어떻게 해야 할까?

In [134]:
(tmp.T + arr).T

array([[ 2,  7, 12, 17],
       [ 5, 10, 15, 20],
       [44, 49, 54, 59],
       [47, 52, 57, 62]])

In [135]:
tmp + arr.reshape((-1, 1))

array([[ 2,  7, 12, 17],
       [ 5, 10, 15, 20],
       [44, 49, 54, 59],
       [47, 52, 57, 62]])

reshape 메소드에서 -1의 의미는 4개의 행이 있어야 하지만, 귀찮으니까 numpy가 알아서 계산해.

In [137]:
arr.reshape((-1, 1))

array([[0],
       [1],
       [2],
       [3]])

In [138]:
ar3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [139]:
ar3d.shape

(3, 4, 5)

In [140]:
ar3d + arr.reshape((-1, 1))

array([[[ 0,  1,  2,  3,  4],
        [ 6,  7,  8,  9, 10],
        [12, 13, 14, 15, 16],
        [18, 19, 20, 21, 22]],

       [[20, 21, 22, 23, 24],
        [26, 27, 28, 29, 30],
        [32, 33, 34, 35, 36],
        [38, 39, 40, 41, 42]],

       [[40, 41, 42, 43, 44],
        [46, 47, 48, 49, 50],
        [52, 53, 54, 55, 56],
        [58, 59, 60, 61, 62]]])

In [142]:
ar3d.shape, arr.shape, arr.reshape((-1, 1)).shape
#(3,4,5) + (4,1) = (3,4,5) + (3,4,5)

((3, 4, 5), (4,), (4, 1))